# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'imageName'

steps:
  - script: docker run quay.io/sysdig/secure-inline-scan:2 -k $(secureApiKey) $(imageName)
    displayName: Scan image
